# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
########################
#                      #
# Author: Robert Patel #
#                      #
########################

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_reportWindow(object):
    def setupUi(self, reportWindow):
        self.current_window = reportWindow
        reportWindow.setObjectName("reportWindow")
        reportWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=reportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.backgroundFrame.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.backgroundFrame.setStyleSheet("background-color:FloralWhite")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.headerBackground = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.headerBackground.setGeometry(QtCore.QRect(0, 0, 801, 80))
        self.headerBackground.setStyleSheet("background-color:DarkSlateGray")
        self.headerBackground.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerBackground.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerBackground.setObjectName("headerBackground")
        self.btnHome = QtWidgets.QPushButton(parent=self.headerBackground)
        self.btnHome.setGeometry(QtCore.QRect(420, 10, 113, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnHome.setFont(font)
        self.btnHome.setStyleSheet("QPushButton {\n"
"                border-radius: 20px;  \n"
"                background-color: FloralWhite;  \n"
"                color: black;\n"
"                font: bold 12px;  \n"
"                padding: 10px 20px;  \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color:DarkSeaGreen; \n"
"            }")
        self.btnHome.setAutoDefault(False)
        self.btnHome.setDefault(False)
        self.btnHome.setObjectName("btnHome")
        self.btnManager = QtWidgets.QPushButton(parent=self.headerBackground)
        self.btnManager.setGeometry(QtCore.QRect(550, 10, 113, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnManager.setFont(font)
        self.btnManager.setStyleSheet("QPushButton {\n"
"                border-radius: 20px;  \n"
"                background-color: FloralWhite;  \n"
"                color: black;\n"
"                font: bold 12px;  \n"
"                padding: 10px 20px;  \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color:DarkSeaGreen; \n"
"            }")
        self.btnManager.setObjectName("btnManager")
        self.btnResults = QtWidgets.QPushButton(parent=self.headerBackground)
        self.btnResults.setGeometry(QtCore.QRect(680, 10, 113, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnResults.setFont(font)
        self.btnResults.setStyleSheet("QPushButton {\n"
"                border-radius: 20px;  \n"
"                background-color: FloralWhite;  \n"
"                color: black;\n"
"                font: bold 12px;  \n"
"                padding: 10px 20px;  \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color:DarkSeaGreen; \n"
"            }")
        self.btnResults.setObjectName("btnResults")
        self.frame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.frame.setGeometry(QtCore.QRect(20, 100, 761, 411))
        self.frame.setStyleSheet("background-color:DarkSlateGray")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.txtReportOutput = QtWidgets.QTextEdit(parent=self.frame)
        self.txtReportOutput.setGeometry(QtCore.QRect(10, 10, 741, 341))
        self.txtReportOutput.setStyleSheet(
            "background-color:FloralWhite; \n" \
            "color: black;")
        self.txtReportOutput.setReadOnly(True)
        self.txtReportOutput.setObjectName("txtReportOutput")
        self.btnExport = QtWidgets.QPushButton(parent=self.frame)
        self.btnExport.setGeometry(QtCore.QRect(10, 360, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnExport.setFont(font)
        self.btnExport.setObjectName("btnExport")
        self.txtReportName = QtWidgets.QLineEdit(parent=self.frame)
        self.txtReportName.setGeometry(QtCore.QRect(140, 360, 221, 31))
        self.txtReportName.setStyleSheet("background-color:FloralWhite")
        self.txtReportName.setObjectName("txtReportName")
        reportWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=reportWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 43))
        self.menubar.setObjectName("menubar")
        reportWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=reportWindow)
        self.statusbar.setObjectName("statusbar")
        reportWindow.setStatusBar(self.statusbar)

        self.retranslateUi(reportWindow)
        QtCore.QMetaObject.connectSlotsByName(reportWindow)
        # Re-opens manager page upon button click.
        self.btnManager.clicked.connect(self.open_manager_page)
        # Opens home page when clicked.
        self.btnHome.clicked.connect(self.open_home_page)
        # Opens the report window when clicked.
        self.btnResults.clicked.connect(self.open_report_page)

    # Helper method used to switch windows.
    def switch_window(self, window_class):
        self.window = QtWidgets.QMainWindow()
        self.ui = window_class()
        self.ui.setupUi(self.window)
        self.window.show()
        self.current_window.close()

    # Method to switch view to manager page.
    def open_manager_page(self):
        from ui.manager import Ui_managerWindow
        self.switch_window(Ui_managerWindow)

    # Method to switch view to home page.
    def open_home_page(self):
        from ui.ai_agent import Ui_mainHomeWindow
        self.switch_window(Ui_mainHomeWindow)

    # Method to switch view to report page.
    def open_report_page(self):
        from ui.report import Ui_reportWindow
        self.switch_window(Ui_reportWindow)

    # Method used to set the text in the text edit.
    def set_report_text(self, text):
        self.txtReportOutput.setPlainText(str(text))

    def retranslateUi(self, reportWindow):
        _translate = QtCore.QCoreApplication.translate
        reportWindow.setWindowTitle(_translate("reportWindow", "Report"))
        self.btnHome.setText(_translate("reportWindow", "Home"))
        self.btnManager.setText(_translate("reportWindow", "Manager"))
        self.btnResults.setText(_translate("reportWindow", "Results"))
        self.btnExport.setText(_translate("reportWindow", "Export Report"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    reportWindow = QtWidgets.QMainWindow()
    ui = Ui_reportWindow()
    ui.setupUi(reportWindow)
    reportWindow.show()
    sys.exit(app.exec())
